/*
--------------------------------------------------------------------------
SQL queries exploring customer and product dimensions against sales data.
Covers customer distribution by country and gender, product breakdown by 
category, average cost and revenue per category, revenue per customer, 
and sold items distribution by country.
--------------------------------------------------------------------------
*/

--Find total customer by countries 
SELECT
COUNT(customer_key) as total_customers,
country
FROM gold.dim_customers 
GROUP BY country 
ORDER by total_customers DESC;

--Find total customers by gender 
SELECT
COUNT(gender) as customers, 
gender
FROM gold.dim_customers 
GROUP BY gender 
ORDER by customers DESC;

--Find total products by category 
SELECT
COUNT(product_key) as total_products, 
category
FROM gold.dim_products
GROUP BY category
ORDER by total_products DESC;

--What is the average costs in each category?
SELECT
avg(cost) as average_price, 
category
FROM gold.dim_products
GROUP BY category
ORDER by average_price DESC;

--What is the total revenue generated for each category?
SELECT
sum(s.sales_amount) as total_revenue, 
p.category
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
ON p.product_key = s.product_key
GROUP BY category
ORDER by total_revenue DESC;

--Find the total revenue generated by each customer 
SELECT
s.customer_key,
c.first_name, 
c.last_name,
sum(s.sales_amount) as total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON s.customer_key = c.customer_key
GROUP BY s.customer_key, c.first_name, c.last_name
ORDER by total_revenue DESC;

--What is the distribution of sold items across countries? 
SELECT
sum(s.quantity) as total_sold_items, 
c.country
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON s.customer_key = c.customer_key
GROUP BY country
ORDER by total_sold_items DESC;
